server.port: 9000
management.endpoints.web.exposure.include: "*"
spring.boot.admin.client.url: http://localhost:9000
management.endpoint.health.show-details: always
org.springframework.security: debug
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: INFO
#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
##          issuer-uri: http://localhost:8180/realms/spring-as
#          jwk-set-uri: http://localhost:8180/realms/spring-as/protocol/openid-connect/certs
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://localhost:8180/realms/spring-as/protocol/openid-connect/certs
oidc.jwk-set-uri: http://localhost:8180/realms/spring-as/protocol/openid-connect/certs
