server.port: 9000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://localhost:8180/realms/spring-as
          jwk-set-uri: http://localhost:8180/realms/spring-as/protocol/openid-connect/certs
